// Copyright 2026 FER, HPC Architecture and Application Research Center
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
//
// Licensed under the Solderpad Hardware License v 2.1 (the "License");
// you may not use this file except in compliance with the License, or,
// at your option, the Apache License version 2.0.
// You may obtain a copy of the License at https://solderpad.org/licenses/SHL-2.1/
//
// Version info is listed in friscv_pkg.sv

/*
 * This module implements the Core Local Interruptor (CLINT) for the FRISC-V reference design.
 * The CLINT maintains a timer (mtime) that increments at a configurable frequency (MTIME_FREQ_HZ),
 * generated by a fractional frequency divider from the input clock (CLK_FREQ_HZ from clk_in).
 *
 * The CLINT is accessed via an AXI4-Lite interface, with the following register map:
 *   0x0000        : msip[0]         (R/W, bit 0 only)
 *   0x4000        : mtimecmp[31:0]  (R/W)
 *   0x4004        : mtimecmp[63:32] (R/W)
 *   0xBFF8        : mtime[31:0]     (R/W)
 *   0xBFFC        : mtime[63:32]    (R/W)
 */

module friscv_clint #(
    parameter [63:0] CLK_FREQ_HZ   = 50_000_000,
    parameter [63:0] MTIME_FREQ_HZ = 10_000_000
) (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk_in CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF s_axi, ASSOCIATED_RESET rstn_in" *)
    input  wire        clk_in,

    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 rstn_in RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire        rstn_in,
    
    output wire [63:0] time_out,

    input  wire [31:0] s_axi_awaddr,
    input  wire        s_axi_awvalid,
    output reg         s_axi_awready,

    input  wire [31:0] s_axi_wdata,
    input  wire        s_axi_wvalid,
    output reg         s_axi_wready,

    output wire [1:0]  s_axi_bresp,
    output reg         s_axi_bvalid,
    input  wire        s_axi_bready,

    input  wire [31:0] s_axi_araddr,
    input  wire        s_axi_arvalid,
    output reg         s_axi_arready,

    output reg  [31:0] s_axi_rdata,
    output wire [1:0]  s_axi_rresp,
    output reg         s_axi_rvalid,
    input  wire        s_axi_rready,

    output wire        msip_out,
    output wire        mtip_out
);

reg [63:0] mtime    = 0;
reg [63:0] mtimecmp = 64'hFFFFFFFFFFFFFFFF;
reg        msip     = 0;
reg [63:0] mtime_frac = 64'b0;

reg [31:0] waddr = 32'b0;
reg [31:0] wdata = 32'b0;
reg awcomplete = 0;
reg wcomplete  = 0;

assign time_out = mtime;

// Write channel
always @(posedge clk_in) begin
    if (!rstn_in) begin
        mtime         <= 64'b0;
        mtimecmp      <= 64'hFFFFFFFFFFFFFFFF;
        msip          <= 1'b0;
        mtime_frac    <= 64'b0;
        waddr         <= 32'b0;
        wdata         <= 32'b0;
        s_axi_awready <= 1'b0;
        s_axi_wready  <= 1'b0;
        s_axi_bvalid  <= 1'b0;
        awcomplete    <= 1'b0;
        wcomplete     <= 1'b0;
    end else begin
        if (MTIME_FREQ_HZ >= CLK_FREQ_HZ) begin
            mtime <= mtime + 1;
        end else if ((mtime_frac + MTIME_FREQ_HZ) >= CLK_FREQ_HZ) begin
            mtime      <= mtime + 1;
            mtime_frac <= (mtime_frac + MTIME_FREQ_HZ) - CLK_FREQ_HZ;
        end else begin
            mtime_frac <= mtime_frac + MTIME_FREQ_HZ;
        end

        if (!awcomplete && !s_axi_awready && s_axi_awvalid) begin
            s_axi_awready <= 1'b1;
        end else if (s_axi_awvalid && s_axi_awready) begin
            waddr         <= s_axi_awaddr;
            s_axi_awready <= 1'b0;
            awcomplete    <= 1'b1;
        end

        if (!wcomplete && !s_axi_wready && s_axi_wvalid) begin
            s_axi_wready <= 1'b1;
        end else if (s_axi_wvalid && s_axi_wready) begin
            wdata        <= s_axi_wdata;
            s_axi_wready <= 1'b0;
            wcomplete    <= 1'b1;
        end

        if (wcomplete && awcomplete && !s_axi_bvalid) begin
            s_axi_bvalid <= 1'b1;
            case (waddr[15:0])
                16'h0000: msip            <= wdata[0];
                16'h4000: mtimecmp[31:0]  <= wdata;
                16'h4004: mtimecmp[63:32] <= wdata;
                16'hBFF8: begin
                    mtime[31:0] <= wdata;
                    mtime_frac  <= 64'b0;
                end
                16'hBFFC: begin
                    mtime[63:32] <= wdata;
                    mtime_frac   <= 64'b0;
                end
                default: ;
            endcase
        end else if (s_axi_bvalid && s_axi_bready) begin
            s_axi_bvalid <= 1'b0;
            wcomplete    <= 1'b0;
            awcomplete   <= 1'b0;
        end
    end
end

// Read channel
always @(posedge clk_in) begin
    if (!rstn_in) begin
        s_axi_arready <= 1'b0;
        s_axi_rvalid  <= 1'b0;
        s_axi_rdata   <= 32'b0;
    end else begin
        if (!s_axi_arready && s_axi_arvalid && !s_axi_rvalid) begin
            s_axi_arready <= 1'b1;
        end else if (s_axi_arvalid && s_axi_arready) begin
            s_axi_arready <= 1'b0;
            s_axi_rvalid  <= 1'b1;
            case (s_axi_araddr[15:0])
                16'h0000: s_axi_rdata <= {31'b0, msip};
                16'h4000: s_axi_rdata <= mtimecmp[31:0];
                16'h4004: s_axi_rdata <= mtimecmp[63:32];
                16'hBFF8: s_axi_rdata <= mtime[31:0];
                16'hBFFC: s_axi_rdata <= mtime[63:32];
                default:  s_axi_rdata <= 32'b0;
            endcase
        end else if (s_axi_rvalid && s_axi_rready) begin
            s_axi_rvalid <= 1'b0;
        end
    end
end

assign s_axi_bresp = 2'b00;
assign s_axi_rresp = 2'b00;
assign msip_out    = msip;
assign mtip_out    = (mtime >= mtimecmp);

endmodule
