#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo
echo "FRISCV Linux booted successfully!"
echo

exec /bin/sh </dev/console >/dev/console 2>/dev/console
