#ifndef _RVTEST_CONFIG_H
#define _RVTEST_CONFIG_H

#define RVMODEL_PMP_GRAIN 0
#define RVMODEL_NUM_PMPS 16

#define S_SUPPORTED
#define SV32_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED

#define TIME_CSR_IMPLEMENTED 1
#define COUNTINHIBIT_EN_0
#define COUNTINHIBIT_EN_2

#endif
