`define XLEN32

`define G 0
`define G_IS_0
`define RVMODEL_ACCESS_FAULT_ADDRESS 32'h00000000
`define CLINT_BASE 32'h02000000

`define S_SUPPORTED
`define SV32_SUPPORTED
`define ZAAMO_SUPPORTED
`define ZALRSC_SUPPORTED
`define COUNTINHIBIT_EN_0
`define COUNTINHIBIT_EN_2
`define TIME_CSR_IMPLEMENTED
